import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import SingleTransaction from '../components/SingleTransaction';
import NewTransaction from '../components/NewTransaction';
import { AppUser } from '../types/user.types';
import BalanceComponent from '../components/BalanceComponent';
import useGetBalance from '../hooks/balance/useGetBalance';
import useGetTransactions from '../hooks/transactions/useGetTransactions';

interface HomePageProps {
  user: AppUser;
}

const Home: NextPage<HomePageProps> = ({ user }) => {
  // state variables
  const { transactions, loadMore, hasNext } = useGetTransactions(user?.uid);
  const { balance } = useGetBalance(user?.uid);

  const [isOpen, setIsOpen] = useState(false);
  const closeModal = () => {
    setIsOpen(false);
  };
  const openModal = () => {
    setIsOpen(true);
  };

  return (
    <>
      <Head>
        <title>Fire Expense</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {balance && <BalanceComponent balance={balance} />}
      <div className="flex w-full justify-between p-4 items-center">
        <h2 className="text-lg">Transactions</h2>
        <button
          type="button"
          onClick={openModal}
          className="px-4 py-2 text-sm font-medium rounded-md border border-slate-300 hover:border-indigo-300"
        >
          Add Transaction
        </button>
      </div>
      <div className="w-full">
        {transactions.map((transaction) => (
          <SingleTransaction key={transaction.id} transaction={transaction} />
        ))}
      </div>
      <button
        type="button"
        onClick={loadMore}
        disabled={!hasNext}
        className="px-4 py-2 mb-4 text-sm font-medium rounded-md border border-slate-300 hover:border-indigo-300 disabled:bg-slate-50 disabled:text-slate-500 disabled:border-slate-200 disabled:shadow-none"
      >
        Load More
      </button>
      <NewTransaction isOpen={isOpen} onClose={closeModal} uid={user?.uid} />
    </>
  );
};

export default Home;
